### PR TITLE
Show contributor/contribution details on mobile

### PR DESCRIPTION
**Pull request by galfert**
Refs #163

On small screens, when selecting a contribution or contributor, the lists are hidden and only the details are shown. The transitions are animated using liquid-fire.

### CODE REVIEW

**Comment by galfert** [comment]
I'm wondering if we should also hide the welcome message when not signed in and showing details. Opinions?

kredits_web

**Comment by skddc** [comment]
> I'm wondering if we should also hide the welcome message when not signed in and showing details. Opinions?

Yes, definitely.

**Comment by galfert** [comment]
Done.

**Comment by galfert** [comment]
Replaced by #169. I removed the transition anymations using liquid-fire, as they were not really working out here.

**Pull request closed without merging**
