### PR TITLE
Update Ember to version 3.8.0

### PR DESCRIPTION
**Pull request by galfert**
At the moment there is still a deprecation warning about ember-browserify left. There is no update for that library yet, and the maintainer recommends to switch to ember-auto-import instead. So far I couldn't get that to work with importing kredits-contracts though.

### CODE REVIEW

**Comment by skddc** [comment]
What's the WIP here actually?

**Comment by galfert** [comment]
What i wrote in the PR description. But it could also be done in a separate PR.

**Comment by skddc** [comment]
Yeah, I think it can/should be a new one, because this seems to be functional on its own and already providing value by upgrading Ember to the latest version.

**Comment by galfert** [comment]
Ok, I removed the WIP from the title

**Pull request merged**
