### PR TITLE
Batch voting

### PR DESCRIPTION
**Pull request by skddc**
Continuation of #62. Rebased branch on master, refactored form styles, updated deps.

Apparently the deployed contract on Kovan doesn't support batch voting yet, or has a bug related to it. I can do transactions for it, but they fail with a contract error.

### CODE REVIEW

**Comment by fsmanuel** [comment]
👍

**Comment by bumi** [comment]
@fsmanuel as you worked on it, can you review the latest status and merge it. 
The kovan contract will at some point support it, nothing (ok, maybe updating kredits-contracts) needs to change for that here.

**Comment by skddc** [comment]
Thing is, we're kind of close to not having any voting at all, and then single vetos will be much more common than batch ones. So I think this branch would need to revert using the +1 buttons as selectors and maybe add actual option fields for rows that one can select.

**Comment by fsmanuel** [comment]
@skddc I'm not sure if I get what you say. Do you want real (ugly) checkboxes? We can change the appearance of the +1 buttons to whatever we want. We just need to talk about how they should look like.
Anyway let me know if I should rebase and continue working on it or how we proceed.

**Comment by skddc** [comment]
No, I want to be able to use the +1 buttons for a single veto/vote, instead of having to press one button, then scroll down, then press another button. The checkboxes can be unstyled and ugly (although I have already designed nice checkboxes; see adding a contributor e.g.). It's an alpha app, and this is all going to change considerably rather soon anyway. I think we can live with some ugly checkboxes, when that doesn't impact UX negatively at the moment.

**Comment by skddc** [comment]
Closing this one for now, because we won't have voting on contributions in the beginning and the UI has to change for that everywhere.

**Pull request closed without merging**
