### PR TITLE
Use new healthcheck API from kredits-contracts

### PR DESCRIPTION
**Pull request by bumi**
This uses console.error to log the healthcheck error.

### CODE REVIEW

**Comment by bumi** [comment]
what do you think? merge it?

**Comment by skddc** [comment]
Don't know what it does. Could you link to the documentation for that healthcheck function?

**Comment by bumi** [comment]
It checks if IPFS is available and if the contracts are found. 
https://github.com/67P/kredits-contracts/blob/master/lib/utils/healthcheck.js#L6

If not it logs an error. 
this is helpful as it might happen in dev mode some times (as it did) and then only causes strange error messages that are not clear and not directly obvious.

**Comment by skddc** [comment]
Hmm, I expected something very different, more like if we have a connection to the Ethereum node or something. How about we rename it in some way that is more expressive about the setup being correct? Like e.g. "checkRequirements" or something.

**Comment by bumi** [comment]
connection is checked... as it loads the code of the address through the ethereum node. 
I don't care that much about the naming, just wanted to have something general as it contains a few checks and can be extended.

**Comment by skddc** [comment]
How about "preflight"?

This is what the process is called in an aircraft, when the pilot checks that everything is ok, before taking off. It's also what they call the CORS OPTIONS requests that ensure one can e.g. POST a thing across JS origins.

**Comment by bumi** [comment]
@skddc renamed the function call. what do you think?

**Comment by skddc** [comment]
@bumi Is this one still relevant?

**Comment by bumi** [comment]
yes, `preflightChecks` tests if and IPFS connection is available and if all the contracts are found. The later is probably not so important anymore because if we have an address of a contract the contract is probably also deployed. 
But I think it is still good to check as one of the main issue has always been the many moving parts that could break.

so tl;dr: yes, I'd still merge it.

**Comment by skddc** [comment]
Ok, want to resolve the merge conflicts in this case?

**Comment by bumi** [comment]
closing this and opening a new one.

**Pull request closed without merging**
