### PR TITLE
Pause app boot until window load event fired

### LINKED ISSUE #17: Fix race condition with user-provided web3
There's currently a race condition where sometimes (for me ~50% or more) the user-provided web3 is loaded on `window`, after it has been checked for in the app. Which results in the app just using its own and pretending the user doesn't have a wallet.

### PR DESCRIPTION
**Pull request by galfert**
Closes #17

Allows the user provided Web3 instance to be inserted before we try to use it.

### CODE REVIEW

**Comment by skddc** [comment]
Should this really be called `web3`, when it's a generic one waiting for the DOM to load?

**Comment by galfert** [comment]
> Should this really be called web3, when it's a generic one waiting for the DOM to load?

I wasn't sure about that either. Do you have a better suggestion?

**Comment by skddc** [comment]
`defer-loading`?

**Comment by galfert** [comment]
Ok, I renamed it.

**Comment by bumi** [comment]
whoot awesome! will test it.

**Comment by skddc** [comment]
Now it works reliably. See commit description and/or IRC. ;)

**Pull request merged**
