### PR TITLE
Use latest node.js LTS on Travis CI

### PR DESCRIPTION
**Pull request by skddc**

### CODE REVIEW

**Comment by skddc** [comment]
I need help with this. Even just installing npm packages fails on precise.

**Comment by gregkare** [comment]
Any reason why you're downgrading from Precise to Trusty instead of upgrading to Xenial? (https://docs.travis-ci.com/user/reference/xenial/)

**Comment by skddc** [comment]
Damn, I thought I was upgrading. Didn't look up names.

**Comment by gregkare** [comment]
Oh yeah, their stupid names... One thing to remember is that they increment letters at every release, but they've reached the end of the alphabet so they're already at C and D again

**Comment by skddc** [comment]
> One thing to remember is that they increment letters at every release

That's a good tip! Thanks.

**Comment by skddc** [comment]
Should be squashed when merged.

**Comment by gregkare** [comment]
Green, squashing!

**Pull request merged**
